// This file is automatically generated. DO NOT EDIT.

package geos

// #include "go-geos.h"
import "C"

import "unsafe"

// #cgo nocallback GEOSArea_r
// #cgo noescape GEOSArea_r

// Area returns g's area.
func (g *Geom) Area() float64 {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	var area float64
	if C.GEOSArea_r(g.context.cHandle, g.cGeom, (*C.double)(&area)) == 0 {
		panic(g.context.err)
	}
	return area
}

// #cgo nocallback GEOSBoundary_r
// #cgo noescape GEOSBoundary_r

// Boundary returns the boundary of g.
func (g *Geom) Boundary() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSBoundary_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSBuffer_r
// #cgo noescape GEOSBuffer_r

// Buffer returns g with the given buffer.
func (g *Geom) Buffer(width float64, quadsegs int) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSBuffer_r(g.context.cHandle, g.cGeom, C.double(width), C.int(quadsegs)), nil)
}

// #cgo nocallback GEOSBufferWithStyle_r
// #cgo noescape GEOSBufferWithStyle_r

// BufferWithStyle returns a buffer using the provided style parameters.
func (g *Geom) BufferWithStyle(width float64, quadsegs int, endCapStyle BufCapStyle, joinStyle BufJoinStyle, mitreLimit float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSBufferWithStyle_r(g.context.cHandle, g.cGeom, C.double(width), C.int(quadsegs), C.int(endCapStyle), C.int(joinStyle), C.double(mitreLimit)), nil)
}

// #cgo nocallback GEOSBuildArea_r
// #cgo noescape GEOSBuildArea_r

// BuildArea returns the polygonization using all the linework, assuming that rings contained within rings are empty holes, rather than extra PolygonHoleSimplify.
func (g *Geom) BuildArea() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSBuildArea_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSGetCentroid_r
// #cgo noescape GEOSGetCentroid_r

// Centroid returns a point at the center of mass of g.
func (g *Geom) Centroid() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSGetCentroid_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSClipByRect_r
// #cgo noescape GEOSClipByRect_r

// ClipByRect returns g clipped to a rectangular polygon.
func (g *Geom) ClipByRect(minX float64, minY float64, maxX float64, maxY float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSClipByRect_r(g.context.cHandle, g.cGeom, C.double(minX), C.double(minY), C.double(maxX), C.double(maxY)), nil)
}

// #cgo nocallback GEOSGeom_clone_r
// #cgo noescape GEOSGeom_clone_r

// Clone returns a clone of g.
func (g *Geom) Clone() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSGeom_clone_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSConcaveHull_r
// #cgo noescape GEOSConcaveHull_r

// ConcaveHull returns the concave hull of g.
func (g *Geom) ConcaveHull(ratio float64, allowHoles uint) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSConcaveHull_r(g.context.cHandle, g.cGeom, C.double(ratio), C.unsigned(allowHoles)), nil)
}

// #cgo nocallback GEOSConcaveHullByLength_r
// #cgo noescape GEOSConcaveHullByLength_r

// ConcaveHullByLength returns the concave hull of g.
func (g *Geom) ConcaveHullByLength(ratio float64, allowHoles uint) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSConcaveHullByLength_r(g.context.cHandle, g.cGeom, C.double(ratio), C.unsigned(allowHoles)), nil)
}

// #cgo nocallback GEOSConstrainedDelaunayTriangulation_r
// #cgo noescape GEOSConstrainedDelaunayTriangulation_r

// ConstrainedDelaunayTriangulation returns the constrained Delaunay triangulation of the vertices of the g.
func (g *Geom) ConstrainedDelaunayTriangulation() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSConstrainedDelaunayTriangulation_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSContains_r
// #cgo noescape GEOSContains_r

// Contains returns true if g contains other.
func (g *Geom) Contains(other *Geom) bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSContains_r(g.context.cHandle, g.cGeom, other.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSConvexHull_r
// #cgo noescape GEOSConvexHull_r

// ConvexHull returns g's convex hull.
func (g *Geom) ConvexHull() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSConvexHull_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSCoverageUnion_r
// #cgo noescape GEOSCoverageUnion_r

// CoverageUnion returns the union of g for polygonal inputs that are correctly noded and do not overlap.
func (g *Geom) CoverageUnion() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSCoverageUnion_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSCoveredBy_r
// #cgo noescape GEOSCoveredBy_r

// CoveredBy returns true if g is covered by other.
func (g *Geom) CoveredBy(other *Geom) bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSCoveredBy_r(g.context.cHandle, g.cGeom, other.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSCovers_r
// #cgo noescape GEOSCovers_r

// Covers returns true if g covers other.
func (g *Geom) Covers(other *Geom) bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSCovers_r(g.context.cHandle, g.cGeom, other.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSCrosses_r
// #cgo noescape GEOSCrosses_r

// Crosses returns true if g crosses other.
func (g *Geom) Crosses(other *Geom) bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSCrosses_r(g.context.cHandle, g.cGeom, other.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSDensify_r
// #cgo noescape GEOSDensify_r

// Densify returns g densified with the given tolerance.
func (g *Geom) Densify(tolerance float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSDensify_r(g.context.cHandle, g.cGeom, C.double(tolerance)), nil)
}

// #cgo nocallback GEOSDifference_r
// #cgo noescape GEOSDifference_r

// Difference returns the difference between g and other.
func (g *Geom) Difference(other *Geom) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newGeom(C.GEOSDifference_r(g.context.cHandle, g.cGeom, other.cGeom), nil)
}

// #cgo nocallback GEOSDifferencePrec_r
// #cgo noescape GEOSDifferencePrec_r

// DifferencePrec returns the difference between g and other.
func (g *Geom) DifferencePrec(other *Geom, gridSize float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newGeom(C.GEOSDifferencePrec_r(g.context.cHandle, g.cGeom, other.cGeom, C.double(gridSize)), nil)
}

// #cgo nocallback GEOSDisjoint_r
// #cgo noescape GEOSDisjoint_r

// Disjoint returns true if g is disjoint from other.
func (g *Geom) Disjoint(other *Geom) bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSDisjoint_r(g.context.cHandle, g.cGeom, other.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSDisjointSubsetUnion_r
// #cgo noescape GEOSDisjointSubsetUnion_r

// DisjointSubsetUnion returns the union of all components of a single geometry (optimized for inputs that can be divided into subsets that do not intersect).
func (g *Geom) DisjointSubsetUnion() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSDisjointSubsetUnion_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSDistance_r
// #cgo noescape GEOSDistance_r

// Distance returns the distance between the closes points on g and other.
func (g *Geom) Distance(other *Geom) float64 {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	var distance float64
	if C.GEOSDistance_r(g.context.cHandle, g.cGeom, other.cGeom, (*C.double)(&distance)) == 0 {
		panic(g.context.err)
	}
	return distance
}

// #cgo nocallback GEOSDistanceIndexed_r
// #cgo noescape GEOSDistanceIndexed_r

// DistanceIndexed returns the distance between g and other, using the indexed facet distance.
func (g *Geom) DistanceIndexed(other *Geom) float64 {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	var distanceIndexed float64
	if C.GEOSDistanceIndexed_r(g.context.cHandle, g.cGeom, other.cGeom, (*C.double)(&distanceIndexed)) == 0 {
		panic(g.context.err)
	}
	return distanceIndexed
}

// #cgo nocallback GEOSDistanceWithin_r
// #cgo noescape GEOSDistanceWithin_r

// DistanceWithin returns whether the distance between g and other is within the given dist.
func (g *Geom) DistanceWithin(other *Geom, dist float64) bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSDistanceWithin_r(g.context.cHandle, g.cGeom, other.cGeom, C.double(dist)) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSGeomGetEndPoint_r
// #cgo noescape GEOSGeomGetEndPoint_r

// EndPoint returns the last point of a LineString.
func (g *Geom) EndPoint() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSGeomGetEndPoint_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSEnvelope_r
// #cgo noescape GEOSEnvelope_r

// Envelope returns the envelope of g.
func (g *Geom) Envelope() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSEnvelope_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSEquals_r
// #cgo noescape GEOSEquals_r

// Equals returns true if g equals other.
func (g *Geom) Equals(other *Geom) bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSEquals_r(g.context.cHandle, g.cGeom, other.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSEqualsExact_r
// #cgo noescape GEOSEqualsExact_r

// EqualsExact returns true if g equals other exactly.
func (g *Geom) EqualsExact(other *Geom, tolerance float64) bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSEqualsExact_r(g.context.cHandle, g.cGeom, other.cGeom, C.double(tolerance)) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSFrechetDistance_r
// #cgo noescape GEOSFrechetDistance_r

// FrechetDistance returns the Fréchet distance between g and other.
func (g *Geom) FrechetDistance(other *Geom) float64 {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	var frechetDistance float64
	if C.GEOSFrechetDistance_r(g.context.cHandle, g.cGeom, other.cGeom, (*C.double)(&frechetDistance)) == 0 {
		panic(g.context.err)
	}
	return frechetDistance
}

// #cgo nocallback GEOSFrechetDistanceDensify_r
// #cgo noescape GEOSFrechetDistanceDensify_r

// FrechetDistanceDensify returns the Fréchet distance between g and other.
func (g *Geom) FrechetDistanceDensify(other *Geom, densifyFrac float64) float64 {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	var frechetDistanceDensify float64
	if C.GEOSFrechetDistanceDensify_r(g.context.cHandle, g.cGeom, other.cGeom, C.double(densifyFrac), (*C.double)(&frechetDistanceDensify)) == 0 {
		panic(g.context.err)
	}
	return frechetDistanceDensify
}

// #cgo nocallback GEOSHasZ_r
// #cgo noescape GEOSHasZ_r

// HasZ returns if g has Z coordinates.
func (g *Geom) HasZ() bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSHasZ_r(g.context.cHandle, g.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSHausdorffDistance_r
// #cgo noescape GEOSHausdorffDistance_r

// HausdorffDistance returns the Hausdorff distance between g and other.
func (g *Geom) HausdorffDistance(other *Geom) float64 {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	var hausdorffDistance float64
	if C.GEOSHausdorffDistance_r(g.context.cHandle, g.cGeom, other.cGeom, (*C.double)(&hausdorffDistance)) == 0 {
		panic(g.context.err)
	}
	return hausdorffDistance
}

// #cgo nocallback GEOSHausdorffDistanceDensify_r
// #cgo noescape GEOSHausdorffDistanceDensify_r

// HausdorffDistanceDensify returns the Hausdorff distance between g and other.
func (g *Geom) HausdorffDistanceDensify(other *Geom, densifyFrac float64) float64 {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	var hausdorffDistanceDensify float64
	if C.GEOSHausdorffDistanceDensify_r(g.context.cHandle, g.cGeom, other.cGeom, C.double(densifyFrac), (*C.double)(&hausdorffDistanceDensify)) == 0 {
		panic(g.context.err)
	}
	return hausdorffDistanceDensify
}

// #cgo nocallback GEOSInterpolate_r
// #cgo noescape GEOSInterpolate_r

// Interpolate returns a point distance d from the start of g, which must be a linestring.
func (g *Geom) Interpolate(d float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newGeom(C.GEOSInterpolate_r(g.context.cHandle, g.cGeom, C.double(d)), nil)
}

// #cgo nocallback GEOSInterpolateNormalized_r
// #cgo noescape GEOSInterpolateNormalized_r

// InterpolateNormalized returns the point that is at proportion from the start.
func (g *Geom) InterpolateNormalized(proportion float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newGeom(C.GEOSInterpolateNormalized_r(g.context.cHandle, g.cGeom, C.double(proportion)), nil)
}

// #cgo nocallback GEOSIntersection_r
// #cgo noescape GEOSIntersection_r

// Intersection returns the intersection of g and other.
func (g *Geom) Intersection(other *Geom) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newGeom(C.GEOSIntersection_r(g.context.cHandle, g.cGeom, other.cGeom), nil)
}

// #cgo nocallback GEOSIntersectionPrec_r
// #cgo noescape GEOSIntersectionPrec_r

// IntersectionPrec returns the intersection of g and other.
func (g *Geom) IntersectionPrec(other *Geom, gridSize float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newGeom(C.GEOSIntersectionPrec_r(g.context.cHandle, g.cGeom, other.cGeom, C.double(gridSize)), nil)
}

// #cgo nocallback GEOSIntersects_r
// #cgo noescape GEOSIntersects_r

// Intersects returns true if g intersects other.
func (g *Geom) Intersects(other *Geom) bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSIntersects_r(g.context.cHandle, g.cGeom, other.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSisClosed_r
// #cgo noescape GEOSisClosed_r

// IsClosed returns true if g is closed.
func (g *Geom) IsClosed() bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSisClosed_r(g.context.cHandle, g.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSisEmpty_r
// #cgo noescape GEOSisEmpty_r

// IsEmpty returns true if g is empty.
func (g *Geom) IsEmpty() bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSisEmpty_r(g.context.cHandle, g.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSisRing_r
// #cgo noescape GEOSisRing_r

// IsRing returns true if g is a ring.
func (g *Geom) IsRing() bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSisRing_r(g.context.cHandle, g.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSisSimple_r
// #cgo noescape GEOSisSimple_r

// IsSimple returns true if g is simple.
func (g *Geom) IsSimple() bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSisSimple_r(g.context.cHandle, g.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSisValid_r
// #cgo noescape GEOSisValid_r

// IsValid returns true if g is valid.
func (g *Geom) IsValid() bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSisValid_r(g.context.cHandle, g.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSLargestEmptyCircle_r
// #cgo noescape GEOSLargestEmptyCircle_r

// LargestEmptyCircle returns the largest empty circle for g, up to a specified tolerance.
func (g *Geom) LargestEmptyCircle(other *Geom, tolerance float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newGeom(C.GEOSLargestEmptyCircle_r(g.context.cHandle, g.cGeom, other.cGeom, C.double(tolerance)), nil)
}

// #cgo nocallback GEOSLength_r
// #cgo noescape GEOSLength_r

// Length returns g's length.
func (g *Geom) Length() float64 {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	var length float64
	if C.GEOSLength_r(g.context.cHandle, g.cGeom, (*C.double)(&length)) == 0 {
		panic(g.context.err)
	}
	return length
}

// #cgo nocallback GEOSLineMerge_r
// #cgo noescape GEOSLineMerge_r

// LineMerge returns a set of fully noded LineStrings, removing any cardinality 2 nodes in the linework.
func (g *Geom) LineMerge() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSLineMerge_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSMakeValid_r
// #cgo noescape GEOSMakeValid_r

// MakeValid repairs an invalid geometry, returning a valid output.
func (g *Geom) MakeValid() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSMakeValid_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSMaximumInscribedCircle_r
// #cgo noescape GEOSMaximumInscribedCircle_r

// MaximumInscribedCircle returns the maximum inscribed circle of g up to the the given tolerance.
func (g *Geom) MaximumInscribedCircle(tolerance float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSMaximumInscribedCircle_r(g.context.cHandle, g.cGeom, C.double(tolerance)), nil)
}

// #cgo nocallback GEOSMinimumClearance_r
// #cgo noescape GEOSMinimumClearance_r

// MinimumClearance returns the minimum clearance of g.
func (g *Geom) MinimumClearance() float64 {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	var minimumClearance float64
	if C.GEOSMinimumClearance_r(g.context.cHandle, g.cGeom, (*C.double)(&minimumClearance)) == 0 {
		panic(g.context.err)
	}
	return minimumClearance
}

// #cgo nocallback GEOSMinimumClearanceLine_r
// #cgo noescape GEOSMinimumClearanceLine_r

// MinimumClearanceLine returns a LineString whose endpoints define the minimum clearance of g.
func (g *Geom) MinimumClearanceLine() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSMinimumClearanceLine_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSMinimumRotatedRectangle_r
// #cgo noescape GEOSMinimumRotatedRectangle_r

// MinimumRotatedRectangle returns the minimum rotated rectangle enclosing g.
func (g *Geom) MinimumRotatedRectangle() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSMinimumRotatedRectangle_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSMinimumWidth_r
// #cgo noescape GEOSMinimumWidth_r

// MinimumWidth returns a linestring geometry which represents the minimum diameter of g.
func (g *Geom) MinimumWidth() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSMinimumWidth_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSNode_r
// #cgo noescape GEOSNode_r

// Node returns a new geometry in which no lines cross each other, and all touching occurs at endpoints.
func (g *Geom) Node() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSNode_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSOffsetCurve_r
// #cgo noescape GEOSOffsetCurve_r

// OffsetCurve returns the offset curve line(s) of g.
func (g *Geom) OffsetCurve(width float64, quadsegs int, joinStyle BufJoinStyle, mitreLimit float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSOffsetCurve_r(g.context.cHandle, g.cGeom, C.double(width), C.int(quadsegs), C.int(joinStyle), C.double(mitreLimit)), nil)
}

// #cgo nocallback GEOSOverlaps_r
// #cgo noescape GEOSOverlaps_r

// Overlaps returns true if g overlaps other.
func (g *Geom) Overlaps(other *Geom) bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSOverlaps_r(g.context.cHandle, g.cGeom, other.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSPointOnSurface_r
// #cgo noescape GEOSPointOnSurface_r

// PointOnSurface returns a point that is inside the boundary of a polygonal geometry.
func (g *Geom) PointOnSurface() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSPointOnSurface_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSProject_r
// #cgo noescape GEOSProject_r

// Project returns the distance of other(a point) projected onto g(a line) from the start of the line.
func (g *Geom) Project(other *Geom) float64 {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return float64(C.GEOSProject_r(g.context.cHandle, g.cGeom, other.cGeom))
}

// #cgo nocallback GEOSProjectNormalized_r
// #cgo noescape GEOSProjectNormalized_r

// ProjectNormalized returns the proportional distance of other(a point) projected onto g(a line) from the start of the line. For example, a point that projects to the middle of a line would be return 0.5.
func (g *Geom) ProjectNormalized(other *Geom) float64 {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return float64(C.GEOSProjectNormalized_r(g.context.cHandle, g.cGeom, other.cGeom))
}

// #cgo nocallback GEOSRelate_r
// #cgo noescape GEOSRelate_r

// Relate returns the DE9IM pattern for g and other.
func (g *Geom) Relate(other *Geom) string {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	relateCStr := C.GEOSRelate_r(g.context.cHandle, g.cGeom, other.cGeom)
	defer C.GEOSFree_r(g.context.cHandle, unsafe.Pointer(relateCStr))
	return C.GoString(relateCStr)
}

// #cgo nocallback GEOSRelateBoundaryNodeRule_r
// #cgo noescape GEOSRelateBoundaryNodeRule_r

// RelateBoundaryNodeRule returns the DE9IM pattern for g and other.
func (g *Geom) RelateBoundaryNodeRule(other *Geom, bnr RelateBoundaryNodeRule) string {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	relateBoundaryNodeRuleCStr := C.GEOSRelateBoundaryNodeRule_r(g.context.cHandle, g.cGeom, other.cGeom, C.int(bnr))
	defer C.GEOSFree_r(g.context.cHandle, unsafe.Pointer(relateBoundaryNodeRuleCStr))
	return C.GoString(relateBoundaryNodeRuleCStr)
}

// #cgo nocallback GEOSReverse_r
// #cgo noescape GEOSReverse_r

// Reverse returns g with sequence orders reversed.
func (g *Geom) Reverse() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSReverse_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSGeom_setPrecision_r
// #cgo noescape GEOSGeom_setPrecision_r

// SetPrecision changes the coordinate precision of g.
func (g *Geom) SetPrecision(gridSize float64, flags PrecisionRule) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSGeom_setPrecision_r(g.context.cHandle, g.cGeom, C.double(gridSize), C.int(flags)), nil)
}

// #cgo nocallback GEOSSharedPaths_r
// #cgo noescape GEOSSharedPaths_r

// SharedPaths returns the paths shared between g and other, which must be lineal geometries.
func (g *Geom) SharedPaths(other *Geom) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newGeom(C.GEOSSharedPaths_r(g.context.cHandle, g.cGeom, other.cGeom), nil)
}

// #cgo nocallback GEOSSimplify_r
// #cgo noescape GEOSSimplify_r

// Simplify returns a simplified geometry.
func (g *Geom) Simplify(tolerance float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSSimplify_r(g.context.cHandle, g.cGeom, C.double(tolerance)), nil)
}

// #cgo nocallback GEOSSnap_r
// #cgo noescape GEOSSnap_r

// Snap returns a geometry with the vertices and segments of g snapped to other within the given tolerance.
func (g *Geom) Snap(other *Geom, tolerance float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newGeom(C.GEOSSnap_r(g.context.cHandle, g.cGeom, other.cGeom, C.double(tolerance)), nil)
}

// #cgo nocallback GEOSGeomGetStartPoint_r
// #cgo noescape GEOSGeomGetStartPoint_r

// StartPoint returns the first point of a LineString.
func (g *Geom) StartPoint() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSGeomGetStartPoint_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSSymDifference_r
// #cgo noescape GEOSSymDifference_r

// SymDifference returns the symmetric difference between g and other.
func (g *Geom) SymDifference(other *Geom) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newGeom(C.GEOSSymDifference_r(g.context.cHandle, g.cGeom, other.cGeom), nil)
}

// #cgo nocallback GEOSSymDifferencePrec_r
// #cgo noescape GEOSSymDifferencePrec_r

// SymDifferencePrec returns the symmetric difference between g and other.
func (g *Geom) SymDifferencePrec(other *Geom, gridSize float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newGeom(C.GEOSSymDifferencePrec_r(g.context.cHandle, g.cGeom, other.cGeom, C.double(gridSize)), nil)
}

// #cgo nocallback GEOSTopologyPreserveSimplify_r
// #cgo noescape GEOSTopologyPreserveSimplify_r

// TopologyPreserveSimplify returns a simplified geometry preserving topology.
func (g *Geom) TopologyPreserveSimplify(tolerance float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSTopologyPreserveSimplify_r(g.context.cHandle, g.cGeom, C.double(tolerance)), nil)
}

// #cgo nocallback GEOSTouches_r
// #cgo noescape GEOSTouches_r

// Touches returns true if g touches other.
func (g *Geom) Touches(other *Geom) bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSTouches_r(g.context.cHandle, g.cGeom, other.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSUnaryUnion_r
// #cgo noescape GEOSUnaryUnion_r

// UnaryUnion returns the union of all components of a single geometry.
func (g *Geom) UnaryUnion() *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSUnaryUnion_r(g.context.cHandle, g.cGeom), nil)
}

// #cgo nocallback GEOSUnaryUnionPrec_r
// #cgo noescape GEOSUnaryUnionPrec_r

// UnaryUnionPrec returns the union of all components of a single geometry.
func (g *Geom) UnaryUnionPrec(gridSize float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newNonNilGeom(C.GEOSUnaryUnionPrec_r(g.context.cHandle, g.cGeom, C.double(gridSize)), nil)
}

// #cgo nocallback GEOSUnion_r
// #cgo noescape GEOSUnion_r

// Union returns the union of g and other.
func (g *Geom) Union(other *Geom) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newGeom(C.GEOSUnion_r(g.context.cHandle, g.cGeom, other.cGeom), nil)
}

// #cgo nocallback GEOSUnionPrec_r
// #cgo noescape GEOSUnionPrec_r

// UnionPrec returns the union of g and other.
func (g *Geom) UnionPrec(other *Geom, gridSize float64) *Geom {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	return g.context.newGeom(C.GEOSUnionPrec_r(g.context.cHandle, g.cGeom, other.cGeom, C.double(gridSize)), nil)
}

// #cgo nocallback GEOSWithin_r
// #cgo noescape GEOSWithin_r

// Within returns true if g is within other.
func (g *Geom) Within(other *Geom) bool {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	switch C.GEOSWithin_r(g.context.cHandle, g.cGeom, other.cGeom) {
	case 0:
		return false
	case 1:
		return true
	default:
		panic(g.context.err)
	}
}

// #cgo nocallback GEOSGeomGetX_r
// #cgo noescape GEOSGeomGetX_r

// X returns g's X coordinate.
func (g *Geom) X() float64 {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	var x float64
	if C.GEOSGeomGetX_r(g.context.cHandle, g.cGeom, (*C.double)(&x)) == 0 {
		panic(g.context.err)
	}
	return x
}

// #cgo nocallback GEOSGeomGetY_r
// #cgo noescape GEOSGeomGetY_r

// Y returns g's Y coordinate.
func (g *Geom) Y() float64 {
	g.context.mutex.Lock()
	defer g.context.mutex.Unlock()
	var y float64
	if C.GEOSGeomGetY_r(g.context.cHandle, g.cGeom, (*C.double)(&y)) == 0 {
		panic(g.context.err)
	}
	return y
}
